// Generated by CoffeeScript 2.4.1
(function() {
  var dispRecords, handleInput, parser, record, rl, updateRecords;

  parser = require("./src/argvParser.js");

  updateRecords = require("./src/updateRecords.js");

  record = parser(process.argv.slice(1));

  rl = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true
  });

  rl.setPrompt("Enter next value: ");

  // dispRecords = ({n, a, h, sd}) ->
  dispRecords = function(r) {
    return console.log(`\tNumber of values:	${r.n}\n\tStandard deviation	${r.rms.toFixed(2)}\n\tArithmetic mean:	${r.a.toFixed(2)}\n\tRoot mean square:	${r.sd.toFixed(2)}\n\tHarmonic mean:		${r.h.toFixed(2)}\n`);
  };

  handleInput = function(input) {
    if (input === "END") {
      process.exit(0);
    }
    record = updateRecords(input, record);
    dispRecords(record);
    return rl.prompt();
  };

  rl.prompt();

  rl.on('line', handleInput);

  rl.on('close', function() {
    return process.exit(84);
  });

}).call(this);
