// Generated by CoffeeScript 2.4.1
(function() {
  var a, h, n, parser, sd;

  parser = require("./src/argvParser.js");

  [n, a, h, sd] = parser(process.argv.slice(1));

  console.log(`n: ${n}\na: ${a}\nh: ${h}\nsd: ${sd}`);

}).call(this);
