// Generated by CoffeeScript 2.4.1
(function() {
  var Record, USAGE, isUint, parser, valuesDesc;

  isUint = require("./utility.js").isUint;

  Record = require("./record.js");

  USAGE = function(bin) {
    return `USAGE\n	${bin} n a h sd\n\nDESCRIPTION\n	n		number of values\n	a		arithmetic mean\n	h		harmonic mean\n	sd		standard deviation`;
  };

  valuesDesc = ["number of values", "arithmetic mean", "harmonic mean", "standard deviation"];

  parser = function(argv) {
    var i, j, values;
    if (argv.length !== 5) {
      console.log(USAGE());
      process.exit(84);
    }
    values = [];
    for (i = j = 1; j <= 4; i = ++j) {
      if (!isUint(argv[i])) {
        console.error(`${argv[i]}: Invalid ${valuesDesc[i - 1]}`);
        process.exit(84);
      }
      values.push(Number(argv[i]));
    }
    return new Record(...values);
  };

  module.exports = parser;

}).call(this);
