// Generated by CoffeeScript 2.4.1
(function() {
  var isUint, updateRecords;

  isUint = require("./utility.js").isUint;

  updateRecords = function(line, record) {
    ++record.n;
    if (!isUint(line)) {
      console.error(`${line}: Invalid value`);
      return process.exit(84);
    }
  };

  module.exports = updateRecords;

}).call(this);
