// Generated by CoffeeScript 2.4.1
(function() {
  var isUint, updateArithmeticMean, updateRecords;

  isUint = require("./utility.js").isUint;

  updateArithmeticMean = function(record, val) {
    return record.a = record.a + (val - record.a) / record.n;
  };

  updateRecords = function(line, record) {
    var val;
    ++record.n;
    if (!isUint(line)) {
      console.error(`${line}: Invalid value`);
      process.exit(84);
    }
    val = Number(line);
    return updateArithmeticMean(record, val);
  };

  module.exports = updateRecords;

}).call(this);
